### ISSUE TITLE
Coverage per bin

### ISSUE THREAD

**Issue by evensannesriiser** [Ecogenomics/CheckM#129]
Hi Donovan,

May I ask you for some brief help on the following questions?:

1) What is actually the best measure/estimate for bin abundance in my 23 samples? Is it percentage of mapped reads, mean contig coverage etc.?

2) Can you shortly describe the difference between the outputs of the "profile" command, i.e. the difference between "% mapped reads" and "% binned populations"?

Currently, I am hoping to find the (mean/median) contig coverage _per bin_. This would be one way to check if my data are "trustworthy"; the higher the coverage the better. I get two outputs from CheckM: 1) Coverage _per contig_ ("coverage" command) and 2) Number and percentage of all reads mapping to a bin ("profile" command). As mentioned, I was hoping to get i.e. "Bin A has a mean coverage of 20 X". Ideally, running the "coverage" command with one .bam file per sample, I would also like to have the coverage per bin _per sample_.

Does this make sense, and is there an easy way to do it? :)

Kind regards,

Even Sannes Riiser,
PhD candidate,
University of Oslo, Norway

**Comment by dparks1134** [comment]
Hello Even,

Many reads may not map to a bin. These reads will often be from low abundant or difficult to assemble or bin populations in  your community. If you want an estimate of the  abundance of your genomes relative to the entire community you need to consider these unmapped reads. The "% mapped reads" column explicitly considers the number of unmapped reads and reports it along the row called "unbinned". This could be a substantial number of the reads and consequently your community. The "% binned populations" gives the relative percentage of each bin you have and completely disregards the unmapped reads. This is only really meaningful from a community perspective if the vast majority of your reads map to bins. Finally, the "% community" column estimates the relative abundance of each of your bins by adjusting for the size of each genome and ASSSUMING a specific average genome size for all unbinned populations. This is an untested assumption, but my best guess is that it probably reasonably accurate, but I can't confirm this.

A good alternative to estimating relative abundance is to look at the relative percentage of single copy genes. You may find SingleM useful for this task: https://github.com/wwood/singlem. This is similar to using 16S rRNA genes to estimate the abundance of organisms except using a gene that is more generally single copy.

You can get the coverage for each of your genomes using the "--coverage_file" flag of the "qa" command:
> checkm qa --coverage_file <coverage_file> <marker_file> <checkm_output_dir>

Cheers,
Donovan

**Comment by evensannesriiser** [comment]
Hi Donovan,

Thank you for giving such thorough answers, that is highly appreciated! :)

Just to be sure I get this right: The "entire community" is represented by all my original, quality filtered reads. The "unmapped reads" used to estimate relative abundance of bins are all the original reads that do not map to the assembly at all, but ALSO the ones mapping to unbinned contigs. Basically all reads not mapping to contigs in bins. Am I correct?

I mapped all my original reads to the assembly, but kept only the _mapped_ reads in the resulting .bam file that I used in the "coverage" command. By keeping only the mapped reads, I guess I lost information of the amount of unmapped reads, and therefore also the ability to calculate relative abundance of the final bins/genomes. Am I right? Should I rather keep _all_ reads in the .bam file after mapping to the assembly, and use this file in the "coverage" command? Does the "coverage" command then treat both reads not mapping to assembly _and_ reads mapping to unbinned contigs when calculating relative abundance of bins?

Hope I'm not too far off here. Again, I really appreciate the help. :)

Best,

Even

**Comment by dparks1134** [comment]
Hey Even. Sorry, I think I lead you astray with my previous answer. The profile command produces a table indicating the percentage of reads **mapped** to an assembly which are assigned to each MAG. This is a useful indication of the relative percentage of different populations within a community when the majority of populations are represented by a MAG and the majority of reads map to the assembly. If the majority of reads do not map to the assembly, these results will not be a reliably indication the relative proportion of different populations.

This limitation could be overcome by requiring unmapped reads to be retained in the BAM file, but this is rarely done. As such, the profile command operates as described above and assumes you are looking to profile the relative percentage of reads that map to the assembled contigs. This is useful for get a sense of the relative abundance of your MAGs, but is only an estimate of the proportion of a community when the vast majority of reads map to the assembly.

**Comment by evensannesriiser** [comment]
Hi Donovan,

Thanks, that certainly cleared things up a little, especially the "mapped reads / %mapped reads" part. Still, there are a few things that still confuses me.

I ran the "coverage" command with a .bam file containing only reads mapping to the assembly, which I understand is perfectly fine (> 95% of my reads map to the assembly). Before running the "profile" command, however, I removed all lines containing "unbinned" (all unbinned contigs) from the coverage file. Was this a mistake? I suspect the unbinned contigs give rise to the "unmapped reads" used to calculate the "% binned population", as this measure "completely disregards the unmapped reads". By removing the "unbinned" contigs from the coverage file, I end up with no unmapped reads at all, only reads mapping to the bins/MAGs. Am I right?

As mentioned, the majority of my reads map to the assembly. After CheckM and RefineM, I get 14 MAGs with completeness > 70%, contamination < 10% and quality measure (completeness - 5X contamination) > 50. Genome sizes between 0.60 - 5.9 Mbp. However, only about 9% of my original reads map to these bins. If I understand you correctly, the output from the "profile" command is not a good measure for the relative abundance of these MAGs in the entire community. Correct? 

Nevertheless, I believe the output may still be useful in looking for statistically significant differences in abundance of these MAGs _between_ the samples. And regarding the relative abundance estimation, I've also performed read based classification using Kaiju, so I already have an estimate.

Hope to get a final answer before Christmas! :) Again, I am thankful for your valuable input!

Best,

Even

**Comment by dparks1134** [comment]
Hello Even,

Yes, you should retain the lines marked as "unbinned" in the file produced by the CheckM coverage command. As you indicated, this is how the number of reads mapped to unbinned contigs is determined.

Given that the majority of your reads do not map to a recovered MAGs, the abundance of these MAGs relative to the entire community will be a somewhat crude estimate. The major issue is that estimating relative community abundance requires adjusting the number of mapped reads to account for the size of the genome (e.g., consider two genomes with the same number of mapped reads, but where one is half the size. The genome that is half the size is actually twice as abundant!). Since there is no way to estimate the size of the genomes comprising the unbinned contigs, some assumptions have to be made. In practice, what I do is just subtract out the percentage of reads mapped to unbinned contigs (e.g., in your case, I assume that 91% of the community will be contained in the unbinned contigs since only 9% of your reads map to recovered MAGs. This may be a fine estimate, but could be wrong depending on the actual size of the genomes making up the unbinned part of the community).

To be precise, the columns of the output table are as follows  (sorry, the math isn't entirely straight forward):

* Bin Id: unique identifier of bin
* Bin size (Mbp): size of bin in Mbp
* mapped reads: number of reads mapped to contigs comprising the bin
* % mapped reads: (reads mapped to bin)/(total number of reads mapped to assembly)
* % binned populations: estimates the proportion of a bin relative to all recovered bins. This is determined from the percentage of reads mapped to a bin normalized for the size of the bin and considering only reads mapped to bins. Specifically, it is calculated as [(% mapped reads)/(bin size)]*(1/C), where C is the sum of size adjusted bin coverages over all bins (i.e., the sum of (% mapped reads)/(bin size) over all bins).
* % community: estimate the proportion of a bin relative to the number of reads mapped to assembled contigs and adjusted for the size of the bin. Assuming the majority of reads map to an assembled contig this is an estimate of the relative proportion of a bin (i.e., population) within the community. It is calculated as the (% binned population) * (100 - (percentage of reads assigned to unbinned contigs))

**Comment by evensannesriiser** [comment]
Dear Donovan,

Happy new year! And thank you for the elaborate answers. Things really start to make sense now. I have only one last question related to basic understanding:

It seems like the "baseline"/"complete" community in your examples is represented by the assembly. What about the portion of reads that did not assemble? In my case, this represent < 5% of the reads. Still, these reads most likely originate from microbes in my sample(s), and are hence part of the microbial community. Would it be right to say that, _ideally_, these reads should be included in calculations of relative abundance?

Nevertheless, I assume taking the assembly as an approximate for the whole community makes sense in  practical terms, and would probably in most cases give an accurate (enough) picture of the microbial communities.

Thanks,

Even

**Comment by evensannesriiser** [comment]
Sounds reasonable! Thank you for all help, looking forward to using more of the "M software".

Good luck with future software development!

Kind regards,

Even Sannes Riiser,
PhD cancidate
University of Oslo, Norway
