### ISSUE TITLE
CheckM problematic on multi-user infrastructure

### ISSUE THREAD

**Issue by pbordron** [Ecogenomics/CheckM#144]
CheckM is problematic on multi-user infrastructures like clusters where ACL forbid users to modify or write in program directories.

If the user needs to change the data root directory (the `checkm data setRoot <directory>` command) to use alternative data, he can't as he cannot write to `DATA_CONFIG`.

Maybe a program option, an env. variable like `$CHECKM_DATA` or an user version of the `DATA_CONFIG` file in the user home (like `~/.checkm` or `~/.config/checkm`) can help user to set his own data directory instead of the one admins will provide (or forgot to provide).

Thank if you can add such functionnality

Philippe

**Comment by dparks1134** [comment]
Thank you for your suggestions. I'm not sure user specific data directories make sense though. The data directory is intended to be the same for all users and be setup during initial program installation. There is no support for users to provide custom data for processing by CheckM. These data files are not provided through pip or GitHub simply due to their size. If essential, CheckM could be installed to a local user directory, but the need to "play" with the data directory is certainly an edge case.
