### ISSUE TITLE
contamination in bins with coverage>1

### ISSUE THREAD

**Issue by AnnSeidel** [Ecogenomics/CheckM#176]
I have a usecase, where I have contigs originating from different samples that are binned together, depending on the genome they belong to. This however results in this genome having a coverage >1 in my bin, as I can have multiple contigs covering the same region in the genome.

When I run checkM on my bin, it reports a contamination in this bin, as it will of course find multiple copies of the marker gene for my genome. However, in my usecase I would not consider this to be a contamination, as both contigs belong to the same genome. Is there any way in checkM to check  if the marker genes might have originated from the same genome?

As a toy example, one could consider the following: take a genome and artificially split it into contigs, then add these contigs into a fasta file twice (i.e. simulating a bin where the original genome has a coverage of 2). Then run checkM as if this fasta file was the result of some binning step.

**Comment by dparks1134** [comment]
Hello. The "strain heterogeneity" field indicates if marker genes identified multiple times are similar to each other and thus likely to be from similar strains. Otherwise, CheckM does consider your bins to be contaminated. Even in the toy example, the bin contain 2 genomes and is thus contaminated based on how contamination is defined in CheckM. In a general sense, I think this is the correct result though I appreciate you may have a specific usecase where this definition of contamination isn't desirable.
