### ISSUE TITLE
checkm database can be dowloaded.

### ISSUE THREAD

**Issue by yyuangy2019** [Ecogenomics/CheckM#228]
Hello, developers.
When I tried to link to the checkm database https://data.ace.uq.edu.au/public/CheckM_databases/, the page couldn't be shown.
The error message is following:
------------------------------------------------------------------------------------------
Forbidden
You don't have permission to access /public/CheckM_databases/ on this server.
------------------------------------------------------------------------------------------
Could you help me to solve this problem?
Thank you for your time!
Best regards!

Y.Guo (Ph.D.)

**Comment by franciscozorrilla** [comment]
Hello, 

I was having the same problem setting up CheckM in my new cluster. 
As discussed in issue #155, their servers are probably down temporarily.
Luckily I had the database file in another cluster and was able to retrieve it.
Unfortunately I cannot upload it to github due to file size limitations, but I was able to upload it to google drive: https://drive.google.com/file/d/1iTtPwt3N_0jA-cmcExapsB28D2sPOI1n/view?usp=sharing
Not sure if this is the latest version, but it works for me.
Hope this helps until the servers are back up.

Best wishes,
FZ

**Comment by yyuangy2019** [comment]
Thank you very much for sharing your personal copy of the CheckM database!
Your help greatly contributed to my current work.
Best regards!
Y.Guo
