### ISSUE TITLE
Can not use checkm in an account.

### ISSUE THREAD

**Issue by Lily-WL** [Ecogenomics/CheckM#260]
Dear Developer,
My checkm can not be used in an account, because the out error as :
 `[Weixin@ts-rd350 ~]$ checkm`
`Traceback (most recent call last):
  File "/usr/bin/checkm", line 36, in <module>
    from checkm import main
ImportError: cannot import name main`.

However, the other account can use checkm normally. 

How can I fix this problem?

Thanks

**Comment by jvollme** [comment]
hi, not a developer but maybe i have got a workaround for you:
It seems this has something to do with how checkm (and it's dependencies) were installed globally on your system. Maybe you could do a local installation of checkm instead?
THis is actually very easy nowadays, without needing any admin rights, using conda and bioconda!

Conda creates local "environments" for you to safely install different stuff into for your own personal use (without modifying the system globally), that otherwise often the sys-admin would need to install. You can also easily switch between different environments with different tools. And you still have access to all sytsem tools, also.

you just download the conda-installer for your system [here ](https://docs.conda.io/en/latest/miniconda.html#linux-installers)(best use the version with "phython 3.7" for "linux 64 bit").

this downloads an installer shell script that you can run without any admin rights. Just make it executable with the following command:
```
chmod ug+x Miniconda3-latest-Linux-x86_64.sh
```

then run the installer as follows:
```
./Miniconda3-latest-Linux-x86_64.sh
```
(you can just answer all prompts with "yes")

then you need to close and reopen your terminal. And you will see that you are in the (base) environment of conda.

You now need to add the bioconda channel (for bioinfo tools such as checkm) by running the following commands:
```
conda config --add channels defaults
conda config --add channels bioconda
conda config --add channels conda-forge
```
now xou can create an environment for checkm like this:

```
conda create -n checkm_env checkm-genome
```

and activate it using:
```
conda activate checkm_env
```

When you fist run checkm you will have to set a data directory with ```checkm Data SetRoot``` and download the checkm datasets into it. [Here](https://hackmd.io/cMQgeGF6TOuuLJvCjQyo0Q) are also some instructions for that.

This should work.
