### ISSUE TITLE
File not found error in checkm

### ISSUE THREAD

**Issue by izhang73** [Ecogenomics/CheckM#274]
Hi! I was previously able to run checkm with no issues, but recently it has been raising a File Not found error: FileNotFoundError: [Errno 2] No such file or directory: 'test/results/storage/tree/concatenated.tre'

I've installed it in a clean conda environment, am using an HPC, and am running it in a directory that should have 1 TB of storage space. I've tried running it in multiple directories and multiple conda environments but it keeps raising the same error. I've also tried it both on the test data and on my own data.

Every post I find online says that this is a memory issue, but I should definitely have plenty of memory. What's going on here?
<img width="938" alt="Screen Shot 2020-08-11 at 11 26 23 AM" src="https://user-images.githubusercontent.com/54910310/89916891-23de4c00-dbc6-11ea-9f20-975ca0347a76.png">

**Comment by dparks1134** [comment]
What command are you running?

**Comment by izhang73** [comment]
I am running checkm lineage_wf -t 8 -x fa ./ checkm

**Comment by dparks1134** [comment]
Hi. It isn't clear what the issue is based on the error message. Can you try upgrading to the latest version of CheckM (v1.1.3) and testing again? There was an issue in prior CheckM versions related to how the latest release of Prodigal handles some FASTA files that has impacted a number of users so perhaps this also explains your results.

**Comment by dparks1134** [comment]
Closing as inactive for >2 weeks.
