### ISSUE TITLE
checkm python compatibility (<v.3.7.12) 

### ISSUE THREAD

**Issue by wshropshire** [Ecogenomics/CheckM#335]
Hello, 

It's worth noting after the recent pull request and the cpython issue that occurs in versions of Python3 >= 3.8 that with the current release, you can only run checkm on python3 versions of 3.7 (with fasta files that have Unix formatted line endings). I'm just posting this to save other people headaches with installation and usage. 

Thank you for this great tool!

Will

**Comment by dparks1134** [comment]
Hi Will,

What is the error message you are getting? I'm able to run the latest version of CheckM (1.2.0) using Python 3.8.10. CheckM doesn't make any direct use of cpython though some of its dependencies might. 

Cheers,
Donovan

**Comment by dparks1134** [comment]
Hi Will,

Sorry - can you confirm this limitation of the Python version is strictly due to the PR by misialq. I don't plan to accept this PR if it is restricting the version of Python 3 that must be used. I appreciate this probably isn't the best for OS X users, but I'm hesitant to force everyone to use a specific version of Python.

Thanks.

**Comment by dparks1134** [comment]
Hi. This is a known issue when using MacOS and Python >=3.8. This has been fixed in the latest release of CheckM (v1.2.1) which is now available on PyPi. I don't maintain the BioConda install of CheckM, but hopefully this will be updated to v1.2.1 shortly.
