### ISSUE TITLE
updated taxonomic data for marker sets?

### ISSUE THREAD

**Issue by george-coulouris** [Ecogenomics/CheckM#398]
@donovan-h-parks,

First off: The Prokaryotic Genome Annotation Pipeline (PGAP) uses CheckM to evaluate the completeness of hundreds of thousands of assemblies. Our use of CheckM has directly improved reference genome selection and enabled the inclusion of MAGs into RefSeq. Thank you!

As you may know, there have been many changes to prokaryotic taxa recently:
https://ncbiinsights.ncbi.nlm.nih.gov/2022/11/14/prokaryotic-phylum-name-changes/

Judging by `checkm_data_2015_01_16.tar.gz`, the names in `taxon_marker_sets.tsv` presumably date from 2015; are there plans to align them with contemporary nomenclature?

Regards,
George Coulouris
National Center for Biotechnology Information (contractor)

**Comment by donovan-h-parks** [comment]
Hi George, 

I'm glad to hear CheckM has been helpful for selecting RefSeq genomes. CheckM v1 is largely deprecated software at this point. I fix breaking bugs, but otherwise development effort is now focused on CheckM v2: https://github.com/chklovski/CheckM2. CheckM v1 and v2, despite having the same name, use different methodologies for estimating genome completeness and contamination. In general, the CheckM v2 estimates will be more accurate though there is some merit to running both.

Cheers,
Donovan

**Comment by azat-badretdin** [comment]
(co-worker of George is here)

Donovan, 

One of the problems of using CheckM v2 at least at the point of checking was that it was not clear what is the target set, on which level of taxonomy. That part was clear in CheckM v1. Now it is not clear what is completeness of genome is measured against?

Is this genome complete as "Bacteria"? Is this genome complete as "Escherichia coli"?

**Comment by donovan-h-parks** [comment]
Indeed. The CheckM v1 and v2 methodologies are very different. In v1, the assessment of genome quality is against a set of presumed single-copy marker genes for a given lineage. CheckM v2 takes a machine learning approach to learn general characteristics about genomes in order to estimate genome quality. As such, this is no concept in CheckM v2 of an assessment being made based on a given taxonomic group. I appreciate this makes CheckM v1 more useful in some cases, and the methods are sufficiently different that they can be seen as two independent estimates of genome quality.

**Comment by george-coulouris** [comment]
Were it provided to you, would you consider incorporating `taxon_marker_sets.tsv` with taxa updated according to NCBI taxonomy?

**Comment by george-coulouris** [comment]
Ok. We can always just fork it. We don't need custom marker sets, we'd just like to update the names on the existing ones. Thanks!
