### ISSUE TITLE
How much is the difference in terms of completeness and contamination of running lineage_wf with the flag reduced_tree ON and  OFF?

### ISSUE THREAD

**Issue by emanuelbecerrasoto** [Ecogenomics/CheckM#53]

**Comment by dparks1134** [comment]
Hello,

 Both trees use the same marker sets. As such, estimates will only differ if using the reduced tree results in a genome being placed in such a way that a different marker set is used (i.e., the genome is assigned to a different lineage). I have only done informal testing, but this case appears very rare and when it does occur the estimates are usual very similar (e.g., a genome being evaluated with the bacterial set instead of the slight more refined proteobacterial set).

Cheers,
Donovan

**Comment by TJrogers86** [comment]
Hello,
I am currently running two programs that both use checkm (metawrap's bin_refinement module and dRep) and I found something that maybe of interest to you. I got what I believe to be significantly different completeness and contamination scores from each programs' output:

bin_refinement checkm results:
![WhatsApp Image 2022-03-09 at 5 38 27 PM](https://user-images.githubusercontent.com/48442658/157551545-244f1ad5-94be-449b-803e-e893014f6a2f.jpeg)

And dRep checkm results
![WhatsApp Image 2022-03-09 at 5 38 22 PM](https://user-images.githubusercontent.com/48442658/157551631-05200b10-2988-42e9-bb23-6b3e90cc78d4.jpeg)

I know for a fact that these are the same bins. So, I decided to dig into each programs' code. I found that bin_refinement uses the  --reduced_tree  as a default, but this isnt stated in the documentation. All this to say, I believe that you can get very different results depending if the --reduced_tree is used or not. Not sure if this would be of interest to you all or not.

**Comment by TJrogers86** [comment]
Also, Im not sure why the N50 would be different in each case
