### ISSUE TITLE
Specify path for tmp directory

### ISSUE THREAD

**Issue by ctSkennerton** [Ecogenomics/CheckM#9]
The /tmp directory on my server is on a separate partition that is limited to 5GB. When running checkM lineage_wf I end up with a whole bunch of errors from hmmer as the tmp directory fills up fast. It would be fantastic if I could specify the directory for all of those tmp files so I can put them in another partition with more space

**Comment by sapuizait** [comment]
Hi, so was this command implemented at some point? I have the same problem

**Comment by Wongolini** [comment]
> 

Yes:
>AREcology_workdir]$ checkm analyze -h
usage: checkm analyze [-h] [--ali] [--nt] [-g] [-x EXTENSION] [-t THREADS] [-q] [--tmpdir TMPDIR] marker_file bin_input output_dir

Identify marker genes in bins and calculate genome statistics.

positional arguments:
  marker_file           markers for assessing bins (marker set or HMM file)
  bin_input             directory containing bins (fasta format) or path to file describing genomes/genes - tab separated in 2 or 3 columns [genome ID, genome fna, genome translation file (pep)]
  output_dir            directory to write output files

optional arguments:
  -h, --help            show this help message and exit
  --ali                 generate HMMER alignment file for each bin
  --nt                  generate nucleotide gene sequences for each bin
  -g, --genes           bins contain genes as amino acids instead of nucleotide contigs
  -x, --extension EXTENSION
                        extension of bins (other files in directory are ignored) (default: fna)
  -t, --threads THREADS
                        number of threads (default: 1)
  -q, --quiet           suppress console output
  **--tmpdir TMPDIR       specify an alternative directory for temporary files**

Example: checkm analyze lineage.ms ./bins ./output
