### ISSUE TITLE
AttributeError: 'module' object has no attribute 'logger'

### ISSUE THREAD

**Issue by GenomicaMicrob** [Ecogenomics/CheckM#91]
After much pain installing checkm (via pip), I get this when I run $checkm:

```
Traceback (most recent call last):
  File "/usr/local/bin/checkm", line 14, in <module>
    logger = checkm.logger
AttributeError: 'module' object has no attribute 'logger'
```

Any ideas?
I am running biolinux 8 in ubuntu 14.04.3 with python 2.7

**Comment by dparks1134** [comment]
Hello,

Can you please confirm that you installed CheckM with <code>sudo pip install checkm-genome</code>? Note that CheckM is installed with <code>checkm-genome</code> and not <code>checkm</code> since, unfortunately, there is another program on pip called checkm.

The CheckM code base has no line with <code>logger = checkm.logger</code>.

Cheers,
Donovan
